name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build

      - name: Debug Info
        run: |
          echo "GitHub Token: ${{ secrets.GITHUB_TOKEN }}"
          echo "Firebase Service Account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEGOCIOKEVIN_52BDA }}"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEGOCIOKEVIN_52BDA }}
          channelId: live
          projectId: negociokevin-52bda
