name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '1//0fWL7SJ-lH89DCgYIARAAGA8SNwF-L9Irk2CPv5M5vd0lUEVvfmfCo587XTxQKoLvYDAhlGhEcDIbEGquxXCzB6CD0Qqna9PLKMA'
          channelId: live
          projectId: 'taqueriaRodo'
